---
- name: 'Setup Extra Common if Stream'
  yum:
    name: "centos-stream-repos"
    state: latest
  tags:
    - packages
  when: 
    - ansible_distribution_major_version == '9'
    - ansible_distribution == 'CentOS'

- name: 'Setup Epel Repository'
  yum:
    name: "{{ epel_repositories_name }}"
    disable_gpg_check: True
    state: "{{ epel_repositories_state }}"
  tags:
    - packages
  when: ansible_os_family == 'RedHat'

- name: 'Enable CentOS-CR Repository'
  ini_file:
    path: /etc/yum.repos.d/CentOS-CR.repo
    section: cr
    option: enabled
    value: '1'
    no_extra_spaces: True
  tags:
    - packages
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'